"""Training configuration classes for LiteReason.

Extends TRL's configuration classes with LiteReason-specific options.
"""

from dataclasses import dataclass, field
from typing import Optional

import trl


@dataclass
class ScriptArguments(trl.ScriptArguments):
    """Extended script arguments for LiteReason training.

    Args:
        dataset_name: Name of the dataset or masking strategy (e.g., "twenty_five_percent")
        dataset_dir: Directory containing train/val JSONL files
        projector_only: If True, freeze base model and only train reasoning projector
    """

    dataset_name: Optional[str] = field(
        default=None,
        # This single field overloads three resolution strategies (see
        # train_sft.py:make_dataset). Whichever you pick, the matching files must
        # have been generated by prepare_sft.py with the corresponding --strategies:
        #   1. Literal stem: loads `train_<dataset_name>.jsonl` directly (e.g.
        #      dataset_name="twenty_five_percent" needs --strategies twenty_five_percent).
        #      Falls back to `train.jsonl` if the prefixed file is absent.
        #   2. Inclusive: if <dataset_name> is one of the masking strategies
        #      (no_masking..full_masking), concatenates `train_<strat>.jsonl` for
        #      every strategy up to and including it -- so all those files must exist.
        #   3. Masked-inclusive: "<strategy>_masked" concatenates the masking
        #      strategies (ten_percent..<strategy>) but excludes no_masking.
        # A mismatch between dataset_name and the generated --strategies surfaces
        # only as a late FileNotFoundError at load time.
        metadata={
            "help": (
                "Dataset name or masking strategy. Either a literal file stem "
                "(loads train_<name>.jsonl), a strategy for inclusive concat "
                "(no_masking..full_masking), or '<strategy>_masked' for "
                "masking-only inclusive concat. Must match prepare_sft.py "
                "--strategies. E.g. twenty_five_percent."
            )
        },
    )
    dataset_dir: Optional[str] = field(
        default=None,
        metadata={"help": "Directory containing train/val JSONL files"},
    )
    projector_only: bool = field(
        default=True,
        metadata={"help": "Freeze base model, only train reasoning projector"},
    )
    max_val_samples: Optional[int] = field(
        default=100,
        metadata={"help": "Maximum validation samples (None for unlimited)"},
    )
    num_reasoning_layers: int = field(
        default=3,
        metadata={"help": "Number of MLP layers in the reasoning projector"},
    )
    max_reasoning_steps: int = field(
        default=5,
        metadata={"help": "Maximum number of reasoning steps per marker"},
    )
    require_implicit_markers: bool = field(
        default=True,
        metadata={
            "help": (
                "Fail training if an SFT sample is missing <implicit_thought> markers. "
                "Disable only for explicit ablations."
            )
        },
    )


@dataclass
class SFTConfig(trl.SFTConfig):
    """Extended SFT configuration for LiteReason.

    Adds three convenience WandB fields (entity, project, run group) on top of
    TRL's SFTConfig.
    """

    wandb_entity: Optional[str] = field(
        default=None,
        metadata={"help": "WandB entity name"},
    )
    wandb_project: Optional[str] = field(
        default=None,
        metadata={"help": "WandB project name"},
    )
    wandb_run_group: Optional[str] = field(
        default=None,
        metadata={"help": "WandB run group"},
    )
